apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud1
  labels:
    pv: owncloud1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/k8s_pv/web/owncloud
