kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: owncloud1-pvc
  namespace: web
  labels:
    app: owncloud1-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
  selector:
    matchLabels:
      pv: owncloud1

