apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
  labels:
    pv: mysql1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/data/web/mysql1
