apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: examplebiubiu
  namespace: tmp
spec:
  secretName: quickstart-example-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 'example.biubiu.org'
  dnsNames:
  - example.biubiu.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.biubiu.org
