apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress1
  labels:
    pv: wordpress1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/k8s_pv/web/wordpress
