kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress1-pvc
  namespace: web
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress1
    app.kubernetes.io/version: "1.0"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      pv: wordpress1
