apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud1
  labels:
    pv: nextcloud1
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/data/web/nextcloud1
