apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb1
  labels:
    pv: mariadb1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/data/web/mariadb
