kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb1-pvc
  labels:
    app: mariadb1-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      pv: mariadb1

