apiVersion: v1
kind: PersistentVolume
metadata:
  name: piwigo1
  labels:
    pv: piwigo1
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/data/web/piwigo
