{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "piwigo.fullname" . }}
  labels:
{{ include "piwigo.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.select }}
  selector:
    matchLabels:
      pv: {{ .Values.persistence.select }}
{{- end }}
{{- end }}
