apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: biubiu-blog-staging
  namespace: web
spec:
  secretName: blog.biubiu-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: blog.biubiu.org
  dnsNames:
  - blog.biubiu.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - blog.biubiu.org
