apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: biubiu-cert-staging
  namespace: web
spec:
  secretName: biubiu-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: biubiu.org
  dnsNames:
  - biubiu.org
  - www.biubiu.org
  - blog.biubiu.org
  - album.biubiu.org
  - cloud.biubiu.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - biubiu.org
      - www.biubiu.org
      - blog.biubiu.org
      - album.biubiu.org
      - cloud.biubiu.org
